# These are supported funding model platforms

# github: [arindamdawn]  # Enable when GitHub Sponsors is set up
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/@schemasentry/core
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

# Currently not accepting donations - project is in early MVP stage.
# May open GitHub Sponsors after v1.0.0 release.
